### ISSUE TITLE
pymssql showing in logs when pyodbc is specified 

### ISSUE THREAD

**Issue by wesseljt** [BuzzCutNorman/tap-mssql#72]
config

```
  - name: tap-mssql--sqlclst-metricssvc
    inherit_from: tap-mssql
    variant: buzzcutnorman
    pip_url: git+https://github.com/BuzzCutNorman/tap-mssql.git
    config:
      dialect: mssql
      driver_type: pyodbc
      database: db1
      user: myuser
      port: 1433
      sqlalchemy_url_query:
        driver: ODBC Driver 17 for SQL Server
        trustServerCertificate: yes
        multiSubnetFailover: yes
      sqlalchemy_eng_params:
        fast_executemany: 'true'
```

inherit from

```
  - name: tap-mssql
    variant: buzzcutnorman
    pip_url: git+https://github.com/BuzzCutNorman/tap-mssql.git
    config:
      dialect: mssql
      driver_type: pyodbc
      port: 1433
      sqlalchemy_url_query:
        Driver: ODBC Driver 17 for SQL Server
      sqlalchemy_eng_params:
        fast_executemany: 'true'
```
